### ISSUE TITLE
Implement a wrapper (EntityWrap) to embed an instance as a component of a dedicated entity.

### ISSUE THREAD

**Issue by Adnn** [ShredEagle/entity#13]
This is notably useful for systems: they tend to be unique and accessed by identity (not iterated via queries), yet they should be stored within the EntityManager for save/load state implementation.

**Comment by Adnn** [comment]
Idea: Some (static) flag in the components that are intended to be accessed via the wrapper only, and thus never iterated. We could fail at compile time if a query over such a component is instantiated.

If only types with this flag can be inside EntityWrap, then Query/EntityWrap are exclusive (and we know that as long as the entity wrap is alive, then component is valid: not necessarily, see below).
Actually, if the type can still be added as component to an entity, then it can be  removed. But would it be possible for this instance to also be in an EntityWrap? If not, we are still good.

**Comment by Adnn** [comment]
I think at the minimum, it will be possible by:
* Querying the archetype on the entity manager (which is 1 indirection to get to the entity manager, then 1 indirection to get to the entity manager state, then the archetype is in a vector directly stored by the state). In particular, no need to query the entity for validity nor for the archetype.
* `Using Archetype::getStorage(StorageIndex<MyComponent>{???})`

**Comment by FranzPoize** [comment]
Do you think it would make sense with an API like that ?
```cpp
EntityWrap<System1, System2, System3> mSystems;
```

```cpp
mSystems{mWorld, {System1param1, System2param}, {System2param1}...}
or
mSystems{mWorld, System1{params...}, System2{params...}...}
```

```cpp
auto & [system1, system2] = mSystems;
```

That removes some indirection and is nice for the structured bindinds API

if you think it makes sense I could try to make the PR

**Comment by Adnn** [comment]
Note: The wrapper template is name `Wrap`.

@FranzPoize: Following this morning discussion's, the intention behind `Wrap` is to keep it a simple "reference like" type to allow implementing class data members that are stored in the EntityManager.

The behaviour you propose could be explicitly requested by clients, by wrapping a `std::tuple<System1, ..., SystemN>` (already offering structured binding). Yet it probably will not make a noticeable difference for a low number of dereference ops.
